[package]
name = "lipi"
version = "0.1.0"
authors = ["Chad Brokaw <cbrokaw@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
parley_data = { git = "https://github.com/linebender/parley" }
parlance = "0.1.0"
icu_properties = "2.1.2"
icu_segmenter = "2.1.2"
icu_locale_core = "2.1.1"

[dev-dependencies]
icu_properties = "2.1.2"
